# Dependencies
markdown:	kramdown
highlighter:	pygments

# Permalinks
permalink:	/blog/:title

# Setup
title:		احسان‌نوشت
tagline:	'blog'
description:	'تارنمای شخصی'
url:		http://camporez.com
commentsystem:	google
disqus:		example

author:
  name:		'احسان مولایی'
  url:		https://about.me/ehsan.molaie

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.jpg

social:
  - icon:	twitter
    url:	https://twitter.com/EhsanMolaie
    desc:	Follow me on twitter

  - icon:	github
    url:	https://github.com/EhsanMolaie
    desc:	Fork me on github

  - icon:	googleplus-alt
    url:	https://plus.google.com/109424431360251307220
    desc:	Add me on google+

  - icon:	feed
    url:	http://camporez.com/atom.xml
    desc:	Subscribe to my feed
    
menu:
  - title:	Home
    url:	/
    
  - title:	About
    url:	/about
    
copyright:
  author:	احسان مولایی
  url:		http://ehsanmolaie.ir
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/2.5

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:
